#!/usr/bin/env python2

import csv
import sys

rd = csv.DictReader(sys.stdin,delimiter="\t")
rownum = 0
for row in rd:

  print "\n#",rownum
  rownum += 1

  for fieldname in rd.fieldnames:
    print "\t"+"{:<30}".format(fieldname)+row[fieldname]
